In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [2]:
data = pd.read_csv("Forest_fire.csv")
data = np.array(data)

In [3]:
data.shape

(39, 5)

In [4]:
data

array([['Jharkand', 40, 45, 20, 1],
       ['Bangalore', 50, 30, 10, 1],
       ['Ecuador', 10, 20, 70, 0],
       ['a', 60, 45, 70, 1],
       ['Bangalore', 30, 48, 10, 1],
       ['c', 50, 15, 30, 0],
       ['de', 5, 35, 35, 0],
       ['asd', 5, 20, 70, 0],
       ['Ecuador', 60, 32, 19, 1],
       ['r', 30, 50, 45, 1],
       ['t', 40, 55, 80, 1],
       ['y', 30, 39, 100, 0],
       ['Jharkand', 10, 12, 12, 0],
       ['Bangalore', 20, 23, 23, 0],
       ['Ecuador', 60, 34, 15, 1],
       ['canada', 80, 4, 68, 0],
       ['c', 25, 56, 79, 1],
       ['c', 12, 45, 90, 0],
       ['asd', 28, 43, 15, 1],
       ['asd', 26, 0, 32, 0],
       ['ad', 32, 37, 21, 1],
       ['sasd', 45, 48, 12, 1],
       ['asd', 56, 15, 65, 0],
       ['asdas', 67, 45, 33, 1],
       ['das', 78, 49, 8, 1],
       ['das', 89, 45, 18, 1],
       ['ads', 21, 12, 44, 0],
       ['ads', 11, 20, 59, 0],
       ['asd', 1, 32, 70, 0],
       [nan, 5, 20, 45, 0],
       [nan, 42, 43, 20, 1],
       [nan, 32, 60

In [5]:
X = data[1:, 1:-1]

In [6]:
X

array([[50, 30, 10],
       [10, 20, 70],
       [60, 45, 70],
       [30, 48, 10],
       [50, 15, 30],
       [5, 35, 35],
       [5, 20, 70],
       [60, 32, 19],
       [30, 50, 45],
       [40, 55, 80],
       [30, 39, 100],
       [10, 12, 12],
       [20, 23, 23],
       [60, 34, 15],
       [80, 4, 68],
       [25, 56, 79],
       [12, 45, 90],
       [28, 43, 15],
       [26, 0, 32],
       [32, 37, 21],
       [45, 48, 12],
       [56, 15, 65],
       [67, 45, 33],
       [78, 49, 8],
       [89, 45, 18],
       [21, 12, 44],
       [11, 20, 59],
       [1, 32, 70],
       [5, 20, 45],
       [42, 43, 20],
       [32, 60, 30],
       [5, 15, 5],
       [20, 30, 5],
       [30, 51, 2],
       [60, 60, 10],
       [10, 10, 60],
       [0, 30, 0],
       [45, 45, 15]], dtype=object)

In [7]:
y = data[1:, -1]

In [8]:
y

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1], dtype=object)

In [9]:
y = y.astype('int')

In [10]:
y

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [11]:
X = X.astype('int')

In [12]:
X

array([[ 50,  30,  10],
       [ 10,  20,  70],
       [ 60,  45,  70],
       [ 30,  48,  10],
       [ 50,  15,  30],
       [  5,  35,  35],
       [  5,  20,  70],
       [ 60,  32,  19],
       [ 30,  50,  45],
       [ 40,  55,  80],
       [ 30,  39, 100],
       [ 10,  12,  12],
       [ 20,  23,  23],
       [ 60,  34,  15],
       [ 80,   4,  68],
       [ 25,  56,  79],
       [ 12,  45,  90],
       [ 28,  43,  15],
       [ 26,   0,  32],
       [ 32,  37,  21],
       [ 45,  48,  12],
       [ 56,  15,  65],
       [ 67,  45,  33],
       [ 78,  49,   8],
       [ 89,  45,  18],
       [ 21,  12,  44],
       [ 11,  20,  59],
       [  1,  32,  70],
       [  5,  20,  45],
       [ 42,  43,  20],
       [ 32,  60,  30],
       [  5,  15,   5],
       [ 20,  30,   5],
       [ 30,  51,   2],
       [ 60,  60,  10],
       [ 10,  10,  60],
       [  0,  30,   0],
       [ 45,  45,  15]])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [26]:
X_train.shape

(26, 3)

In [27]:
X_test.shape

(12, 3)

In [28]:
log_reg = LogisticRegression()

In [29]:
log_reg.fit(X_train, y_train)

LogisticRegression()

In [30]:
inputt=[int(x) for x in "45 32 60".split(' ')]

In [31]:
inputt

[45, 32, 60]

In [42]:
final=[np.array(inputt)]

In [43]:
final

[array([45, 32, 60])]

In [44]:
b = log_reg.predict_proba(final)

In [45]:
b

array([[0.14459396, 0.85540604]])